{
  "tagFormat": "v${version}",
  "branches": [
    "master",
    {
      "name": "beta",
      "prerelease": true,
      "channel": "beta"
    }
  ],
  "plugins": [
    ["@semantic-release/commit-analyzer", { "preset": "angular" }],
    "@semantic-release/release-notes-generator",
    ["@semantic-release/changelog", { "preset": "angular" }],
    ["@semantic-release/npm", { "npmPublish": false, "pkgRoot": "ads.manager/Packages/com.thelegends.ads.manager" }],
    ["@semantic-release/git", {
      "assets": ["ads.manager/Packages/com.thelegends.ads.manager/package.json", "CHANGELOG.md"],
      "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    }],
    "@semantic-release/github"
  ]
}
