{
  "tagFormat": "v${version}",
  "plugins": [
    ["@semantic-release/commit-analyzer", { "preset": "angular" }],
    "@semantic-release/release-notes-generator",
    ["@semantic-release/changelog", { 
      "preset": "angular",
      "changelogFile": "TheLegends.Base.TestUPM/Packages/com.thelegends.base.testupm/CHANGELOG.md"
    }],
    ["@semantic-release/npm", { "npmPublish": false, "pkgRoot": "TheLegends.Base.TestUPM/Packages/com.thelegends.base.testupm" }],
    ["@semantic-release/git", {
      "assets": [
        "TheLegends.Base.TestUPM/Packages/com.thelegends.base.testupm/package.json",
        "TheLegends.Base.TestUPM/Packages/com.thelegends.base.testupm/CHANGELOG.md",
        "CHANGELOG.md"
      ],
      "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    }],
    "@semantic-release/github"
  ]
}