name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Semantic release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create upm branch
        uses: RageAgainstThePixel/upm-subtree-split@v1
#  publish:
#    needs: release
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          ref: upm
#      - uses: bahmutov/npm-install@v1
#        with:
#          useLockFile: false
#      - uses: JS-DevTools/npm-publish@v3
#        with:
#          token: ${{ secrets.VERDACCIO_TOKEN }}
#          registry: ${{ secrets.VERDACCIO_URL }}  