name: Publish
on:
  push:
    tags:
    - '1.1.18'
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: upm
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm test
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.VERDACCIO_TOKEN }}
          registry: "https://verdaccio.tripdev.io"