name: Publish Unity Package to Verdaccio
on:
  push:
    branches:
    - upm
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: upm
    - name: Publish with Verdaccio
      uses: verdaccio/github-actions/publish@master
      with:
        registry_url: ${{ secrets.VERDACCIO_URL }}
        username: ${{ secrets.VERDACCIO_USERNAME }}
        password: ${{ secrets.VERDACCIO_PASSWORD }}
        email: ${{ secrets.VERDACCIO_EMAIL }}